export const ADDRESSES = {
    ETHEREUM_GOVERNANCE_EXECUTOR: process.env.ETHEREUM_GOVERNANCE_EXECUTOR_ADDRESS,
    GUARDIAN: process.env.GUARDIAN_ADDRESS,
    L2_ERC20_BRIDGE: process.env.L2_ERC20_BRIDGE_ADDRESS,
    ZERO: '0x0000000000000000000000000000000000000000',
};

export const GOVERNANCE_CONSTANTS = {
    DELAY: process.env.EXECUTION_DELAY,
    GRACE_PERIOD: process.env.EXECUTION_GRACE_PERIOD,
    MIN_DELAY: process.env.EXECUTION_MIN_DELAY,
    MAX_DELAY: process.env.EXECUTION_MAX_DELAY,
};

export const ERC20_BRIDGED_CONSTANTS = {
    NAME: 'Wrapped liquid staked Ether 2.0',
    SYMBOL: 'wstETH',
    DECIMALS: 18
};
