export const ADDRESSES = {
    ETHEREUM_GOVERNANCE_EXECUTOR: process.env.ETHEREUM_GOVERNANCE_EXECUTOR_ADDRESS,
    GUARDIAN: process.env.GUARDIAN_ADDRESS,
};

export const CONSTANTS = {
    DELAY: process.env.EXECUTION_DELAY,
    GRACE_PERIOD: process.env.EXECUTION_GRACE_PERIOD,
    MIN_DELAY: process.env.EXECUTION_MIN_DELAY,
    MAX_DELAY: process.env.EXECUTION_MAX_DELAY,
};
