name: Code Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  slither:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup node.js version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install node deps
        run: npm ci

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10.6"

      - name: Install poetry requirements
        run: >
          curl -sSL https://install.python-poetry.org | python - &&
          poetry install --no-root

      - name: Run slither
        run: >
          poetry run slither . --sarif results.sarif || true

      - name: Check results.sarif presence
        id: results
        if: always()
        shell: bash
        run: >
          test -f results.sarif &&
          echo 'value=present' >> $GITHUB_OUTPUT ||
          echo 'value=not' >> $GITHUB_OUTPUT

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: ${{ always() && steps.results.outputs.value == 'present' }}
        with:
          sarif_file: results.sarif

  solhint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup node.js version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 16.x

      - name: Install solhint
        run: >
          npm install solhint solhint-plugin-lido

      - name: Run solhint
        run: >
          npx solhint 'contracts/**/*.sol'
